### ISSUE TITLE
In DBHandler in the DBEmployees class there are two errors.

### ISSUE THREAD

**Issue by claytonr1** [claytonr1/TeamMefford#2]
At line 42, the getID method uses a string parameter just as getID method at line 27 does.  C# cannot distinguish method names by the names of their parameters.  To the compiler, these method signatures are identical because the method name and the data type of the parameter are the same.  

A similar issue exists down at line 62 for containsEmployee.  This is for the code in the WebJet.

**Comment by timoglor** [comment]
I took care of it.
